export interface ExtractSetupWebviewData {
  language: string;
  hasDetectedLangs: boolean;
  isFirstSetup: boolean;
  langAliasCustomMappings: Record<string, string[]>;
  availableLanguages: Array<{ code: string; label: string }>;
  defaults: {
    framework: string;
    languagePath: string;
    fileExtensions: string[];
    vueTemplateFunctionName: string;
    vueScriptFunctionName: string;
    jsTsFunctionName: string;
    vueScriptImportLines: string[];
    vueScriptSetupLines: string[];
    jsTsImportLines: string[];
    jsTsSetupLines: string[];
    skipJsTsInjection: boolean;
    skipVueScriptInjection: boolean;
    keyPrefix: "none" | "auto-path";
    languageStructure: "flat" | "nested";
    sortRule: "none" | "byKey" | "byPosition";
    keyStrategy: "english" | "pinyin";
    keyStyle: "camelCase" | "PascalCase" | "snake_case" | "kebab-case" | "raw";
    maxKeyLength: number;
    invalidKeyStrategy: "fallback" | "ai";
    indentType: "auto" | "space" | "tab";
    indentSize: number | null;
    quoteStyleForKey: "none" | "single" | "double" | "auto";
    quoteStyleForValue: "single" | "double" | "auto";
    stopWords: string[];
    stopPrefixes: string[];
    onlyExtractSourceLanguageText: boolean;
    referenceLanguage: string;
    translationFileType: "json" | "json5" | "js" | "ts" | "yaml" | "yml";
    extractScopePaths: string[];
    ignoreExtractScopePaths: string[];
    targetLanguages: string[];
    vueTemplateIncludeAttrs: string[];
    vueTemplateExcludeAttrs: string[];
    ignoreTexts: string[];
    ignoreCallExpressionCallees: string[];
    translationFailureStrategy: "skip" | "fill-with-source" | "abort";
  };
}
