import * as vscode from "vscode";
import { registerCheckUsageCommand } from "./inspection/checkUsageCommand";
import { registerMarkAsKnownLangCommand } from "./mark/markAsKnownLangCommand";
import { registerSetReferredLangCommand } from "./config/setReferredLangCommand";
import { registerMarkAsUsedCommand } from "./mark/markAsUsedCommand";
import { registerSelectLangPathCommand } from "./config/selectLangPathCommand";
import { registerSetLangPathCommand } from "./config/setLangPathCommand";
import { registerSetProjectPathCommand } from "./config/setProjectPathCommand";
import { registerCopyEntriesCommand } from "./copy/copyEntriesCommand";
import { registerCopyNameCommand } from "./copy/copyNameCommand";
import { registerCopyValueCommand } from "./copy/copyValueCommand";
import { registerDeleteUnusedCommand } from "./fix/deleteUnusedCommand";
import { registerEditValueCommand } from "./fix/editValueCommand";
import { registerFixCommand } from "./fix/fixCommand";
import { registerSortCommand } from "./fix/sortCommand";
import { registerExportCommand } from "./excel/exportCommand";
import { registerImportCommand } from "./excel/importCommand";
import { registerExcelCommand } from "./excel/excelCommand";
import { registerExportDiffCommand } from "./excel/exportDiffCommand";
import { registerImportDiffCommand } from "./excel/importDiffCommand";
import { registerGoToDefinitionCommand } from "./inspection/goToDefinitionCommand";
import { registerGoToReferenceCommand } from "./inspection/goToReferenceCommand";
import { registerFindReferencesCommand } from "./inspection/findReferencesCommand";
import { registerIgnoreFileCommand } from "./ignore/ignoreFileCommand";
import { registerSetDisplayLangCommand } from "./config/setDisplayLangCommand";
import { registerIgnoreDirectoryCommand } from "./ignore/ignoreDirectoryCommand";
import { registerIgnoreLangCommand } from "./ignore/ignoreLangCommand";
import { registerUnignoreLangCommand } from "./ignore/unignoreLangCommand";
import { registerUnmarkAsUsedCommand } from "./mark/unmarkAsUsedCommand";
import { registerToggleInlineTranslationCommand } from "./config/toggleInlineTranslationCommand";
import { registerIgnoreUndefinedCommand } from "./ignore/ignoreUndefinedCommand";
import { registerFeedbackCommand } from "./guide/feedbackCommand";
import { registerOpenSettingsCommand } from "./guide/openSettingsCommand";
import { registerOpenDocsCommand } from "./guide/openDocsCommand";
import { registerStarCommand } from "./guide/starCommand";
import { registerBrowseTranslationsInFileCommand } from "./inspection/browseTranslationsInFileCommand";
import { registerRewriteEntryCommand } from "./fix/rewriteEntryCommand";
import { registerSearchCommand } from "./search/searchCommand";
import { registerCancelSearchCommand } from "./search/cancelSearchCommand";
import { registerToggleWholeWordMatchCommand } from "./search/toggleWholeWordMatchCommand";
import { registerToggleCaseSensitiveCommand } from "./search/toggleCaseSensitiveCommand";
import { registerPasteEntriesCommand } from "./copy/pasteEntriesCommand";
import { registerExtractHardcodedTextsCommand } from "./extract/extractHardcodedTextsCommand";

export function registerAllCommands(context: vscode.ExtensionContext) {
  registerCheckUsageCommand();
  registerMarkAsKnownLangCommand();
  registerSetReferredLangCommand();
  registerMarkAsUsedCommand();
  registerSelectLangPathCommand();
  registerSetLangPathCommand();
  registerSetProjectPathCommand();
  registerCopyEntriesCommand();
  registerCopyNameCommand();
  registerCopyValueCommand();
  registerDeleteUnusedCommand();
  registerEditValueCommand();
  registerFixCommand(context);
  registerSortCommand();
  registerExcelCommand();
  registerExportCommand();
  registerExportDiffCommand();
  registerImportCommand(context);
  registerImportDiffCommand(context);
  registerGoToDefinitionCommand();
  registerGoToReferenceCommand();
  registerFindReferencesCommand();
  registerIgnoreFileCommand();
  registerSetDisplayLangCommand();
  registerIgnoreDirectoryCommand();
  registerIgnoreLangCommand();
  registerUnignoreLangCommand();
  registerUnmarkAsUsedCommand();
  registerToggleInlineTranslationCommand();
  registerIgnoreUndefinedCommand();
  registerFeedbackCommand();
  registerOpenDocsCommand();
  registerOpenSettingsCommand();
  registerStarCommand();
  registerBrowseTranslationsInFileCommand();
  registerRewriteEntryCommand();
  registerSearchCommand();
  registerCancelSearchCommand();
  registerToggleWholeWordMatchCommand();
  registerToggleCaseSensitiveCommand();
  registerPasteEntriesCommand(context);
  registerExtractHardcodedTextsCommand(context);
}
