import * as vscode from "vscode";
import { registerCheckUsageCommand } from "./check/checkUsageCommand";
import { registerMarkAsKnownLangCommand } from "./mark/markAsKnownLangCommand";
import { registerSetReferredLangCommand } from "./config/setReferredLangCommand";
import { registerMarkAsUsedCommand } from "./mark/markAsUsedCommand";
import { registerSelectLangPathCommand } from "./config/selectLangPathCommand";
import { registerSetLangPathCommand } from "./config/setLangPathCommand";
import { registerSetProjectPathCommand } from "./config/setProjectPathCommand";
import { registerCopyKeyValueCommand } from "./copy/copyKeyValueCommand";
import { registerCopyNameCommand } from "./copy/copyNameCommand";
import { registerCopyValueCommand } from "./copy/copyValueCommand";
import { registerDeleteUnusedCommand } from "./fix/deleteUnusedCommand";
import { registerEditValueCommand } from "./fix/editValueCommand";
import { registerFixCommand } from "./fix/fixCommand";
import { registerSortCommand } from "./fix/sortCommand";
import { registerExportCommand } from "./importExport/exportCommand";
import { registerImportCommand } from "./importExport/importCommand";
import { registerGoToDefinitionCommand } from "./search/goToDefinitionCommand";
import { registerGoToReferenceCommand } from "./search/goToReferenceCommand";
import { registerIgnoreFileCommand } from "./ignore/ignoreFileCommand";
import { registerSetDisplayLangCommand } from "./config/setDisplayLangCommand";
import { registerIgnoreDirectoryCommand } from "./ignore/ignoreDirectoryCommand";
import { registerIgnoreLangCommand } from "./ignore/ignoreLangCommand";
import { registerUnignoreLangCommand } from "./ignore/unignoreLangCommand";
import { registerUnmarkAsUsedCommand } from "./mark/unmarkAsUsedCommand";
import { registerToggleInlineTranslationCommand } from "./config/toggleInlineTranslationCommand";
import { registerIgnoreUndefinedCommand } from "./ignore/ignoreUndefinedCommand";
import { registerFeedbackCommand } from "./guide/feedbackCommand";
import { registerOpenSettingsCommand } from "./guide/openSettingsCommand";
import { registerOpenDocsCommand } from "./guide/openDocsCommand";
import { registerStarCommand } from "./guide/starCommand";
import { registerBrowseTranslationsInFileCommand } from "./search/browseTranslationsInFile";
import { registerRewriteEntryCommand } from "./fix/rewriteEntryCommand";

export function registerAllCommands(context: vscode.ExtensionContext) {
  registerCheckUsageCommand();
  registerMarkAsKnownLangCommand();
  registerSetReferredLangCommand();
  registerMarkAsUsedCommand();
  registerSelectLangPathCommand();
  registerSetLangPathCommand();
  registerSetProjectPathCommand();
  registerCopyKeyValueCommand();
  registerCopyNameCommand();
  registerCopyValueCommand();
  registerDeleteUnusedCommand();
  registerEditValueCommand();
  registerFixCommand(context);
  registerSortCommand();
  registerExportCommand();
  registerImportCommand(context);
  registerGoToDefinitionCommand();
  registerGoToReferenceCommand();
  registerIgnoreFileCommand();
  registerSetDisplayLangCommand();
  registerIgnoreDirectoryCommand();
  registerIgnoreLangCommand();
  registerUnignoreLangCommand();
  registerUnmarkAsUsedCommand();
  registerToggleInlineTranslationCommand();
  registerIgnoreUndefinedCommand();
  registerFeedbackCommand();
  registerOpenDocsCommand();
  registerOpenSettingsCommand();
  registerStarCommand();
  registerBrowseTranslationsInFileCommand();
  registerRewriteEntryCommand();
}
