import { KEY_STYLE } from "@/types";
import { LangContextInternal } from "@/types/context";

export const createLangContext = (): LangContextInternal => ({
  task: "",
  langPath: "",
  langFileType: "",
  projectPath: "",
  ignoredLangs: [],
  globalFlag: false,
  rewriteFlag: false,
  exportDir: "",
  cachePath: "",
  styleScore: 0,
  fileStructure: null,
  modifyList: [],
  sortingWriteMode: "none",
  sortingExportMode: "none",
  matchExistingKey: true,
  autoTranslateMissingKey: false,
  validateLanguageBeforeTranslate: true,
  generatedKeyStyle: KEY_STYLE.camelCase,
  stopWords: [],
  maxGeneratedKeyLength: 40,
  keyPrefix: "",
  languageFileIndent: 0,
  quoteStyleForKey: "auto",
  quoteStyleForValue: "auto",
  i18nFramework: "none",
  checkUsageWithStringLiterals: true,

  langDictionary: {},
  langCountryMap: {},
  lackInfo: {},
  extraInfo: {},
  nullInfo: {},
  singleLangRepeatTextInfo: {},
  multiLangRepeatTextInfo: {},
  entryClassTree: {},
  entryClassInfo: {},
  undefinedEntryList: [],
  undefinedEntryMap: {},
  usedEntryMap: {},
  usedKeySet: new Set<string>(),
  unusedKeySet: new Set<string>(),
  isFlat: true,
  langFileExtraInfo: {},
  isVacant: true,
  entryTree: {},
  updatedEntryValueInfo: {},
  patchedEntryIdInfo: {},
  referredLang: "",
  displayLang: "",
  defaultLang: "en",
  importExcelFrom: "",
  importSheetData: "",
  exportExcelTo: "",
  clearCache: true,
  syncBasedOnReferredEntries: false,
  trimKeyList: [],
  manuallyMarkedUsedEntries: [],
  nameSeparator: ""
});
